# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ae2ebd7
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: false
github_repo_name: c-therm-tci
project_description: Process data exported from the C-Therm TCi thermal conductivity
    analyzer.
project_email: blake.naccarato@gmail.com
project_name: c_therm_tci
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2024
